<?php
return apply_filters(
	'lp-open-ai-modal-config',
	[
		'language'                  => [
			'US English' => esc_html__( 'US English', 'learnpress' ),
			'UK English' => esc_html__( 'UK English', 'learnpress' ),
			'Arabic'     => esc_html__( 'Arabic', 'learnpress' ),
			'Bulgarian'  => esc_html__( 'Bulgarian', 'learnpress' ),
			'Chinese'    => esc_html__( 'Chinese', 'learnpress' ),
			'Czech'      => esc_html__( 'Czech', 'learnpress' ),
			'Danish'     => esc_html__( 'Danish', 'learnpress' ),
			'Dutch'      => esc_html__( 'Dutch', 'learnpress' ),
			'Estonian'   => esc_html__( 'Estonian', 'learnpress' ),
			'Finnish'    => esc_html__( 'Finnish', 'learnpress' ),
			'French'     => esc_html__( 'French', 'learnpress' ),
			'German'     => esc_html__( 'German', 'learnpress' ),
			'Greek'      => esc_html__( 'Greek', 'learnpress' ),
			'Hebrew'     => esc_html__( 'Hebrew', 'learnpress' ),
			'Hungarian'  => esc_html__( 'Hungarian', 'learnpress' ),
			'Indonesian' => esc_html__( 'Indonesian', 'learnpress' ),
			'Italian'    => esc_html__( 'Italian', 'learnpress' ),
			'Japanese'   => esc_html__( 'Japanese', 'learnpress' ),
			'Korean'     => esc_html__( 'Korean', 'learnpress' ),
			'Latvian'    => esc_html__( 'Latvian', 'learnpress' ),
			'Lithuanian' => esc_html__( 'Lithuanian', 'learnpress' ),
			'Norwegian'  => esc_html__( 'Norwegian', 'learnpress' ),
			'Polish'     => esc_html__( 'Polish', 'learnpress' ),
			'Portuguese' => esc_html__( 'Portuguese', 'learnpress' ),
			'Romanian'   => esc_html__( 'Romanian', 'learnpress' ),
			'Russian'    => esc_html__( 'Russian', 'learnpress' ),
			'Slovak'     => esc_html__( 'Slovak', 'learnpress' ),
			'Slovenian'  => esc_html__( 'Slovenian', 'learnpress' ),
			'Spanish'    => esc_html__( 'Spanish', 'learnpress' ),
			'Swedish'    => esc_html__( 'Swedish', 'learnpress' ),
			'Turkish'    => esc_html__( 'Turkish', 'learnpress' ),
			'Vietnamese' => esc_html__( 'Vietnamese', 'learnpress' ),
		],
		'audience'                  => [
			'Activists'                => esc_html__( 'Activists', 'learnpress' ),
			'Artists'                  => esc_html__( 'Artists', 'learnpress' ),
			'Authors'                  => esc_html__( 'Authors', 'learnpress' ),
			'Bargain Hunters'          => esc_html__( 'Bargain Hunters', 'learnpress' ),
			'Bloggers'                 => esc_html__( 'Bloggers', 'learnpress' ),
			'Business Owners'          => esc_html__( 'Business Owners', 'learnpress' ),
			'Collectors'               => esc_html__( 'Collectors', 'learnpress' ),
			'Cooks'                    => esc_html__( 'Cooks', 'learnpress' ),
			'Crafters'                 => esc_html__( 'Crafters', 'learnpress' ),
			'Dancers'                  => esc_html__( 'Dancers', 'learnpress' ),
			'DIYers'                   => esc_html__( 'DIYers', 'learnpress' ),
			'Designers'                => esc_html__( 'Designers', 'learnpress' ),
			'Educators'                => esc_html__( 'Educators', 'learnpress' ),
			'Engineers'                => esc_html__( 'Engineers', 'learnpress' ),
			'Entrepreneurs'            => esc_html__( 'Entrepreneurs', 'learnpress' ),
			'Environmentalists'        => esc_html__( 'Environmentalists', 'learnpress' ),
			'Fashionistas'             => esc_html__( 'Fashionistas', 'learnpress' ),
			'Fitness Enthusiasts'      => esc_html__( 'Fitness Enthusiasts', 'learnpress' ),
			'Foodies'                  => esc_html__( 'Foodies', 'learnpress' ),
			'Gaming Enthusiasts'       => esc_html__( 'Gaming Enthusiasts', 'learnpress' ),
			'Gardeners'                => esc_html__( 'Gardeners', 'learnpress' ),
			'General Audience'         => esc_html__( 'General Audience', 'learnpress' ),
			'Health Enthusiasts'       => esc_html__( 'Health Enthusiasts', 'learnpress' ),
			'Healthcare Professionals' => esc_html__( 'Healthcare Professionals', 'learnpress' ),
			'Indoor Hobbyists'         => esc_html__( 'Indoor Hobbyists', 'learnpress' ),
			'Investors'                => esc_html__( 'Investors', 'learnpress' ),
			'Job Seekers'              => esc_html__( 'Job Seekers', 'learnpress' ),
			'Movie Buffs'              => esc_html__( 'Movie Buffs', 'learnpress' ),
			'Musicians'                => esc_html__( 'Musicians', 'learnpress' ),
			'Outdoor Enthusiasts'      => esc_html__( 'Outdoor Enthusiasts', 'learnpress' ),
			'Parents'                  => esc_html__( 'Parents', 'learnpress' ),
			'Pet Owners'               => esc_html__( 'Pet Owners', 'learnpress' ),
			'Photographers'            => esc_html__( 'Photographers', 'learnpress' ),
			'Podcast Listeners'        => esc_html__( 'Podcast Listeners', 'learnpress' ),
			'Professionals'            => esc_html__( 'Professionals', 'learnpress' ),
			'Retirees'                 => esc_html__( 'Retirees', 'learnpress' ),
			'Russian'                  => esc_html__( 'Russian', 'learnpress' ),
			'Seniors'                  => esc_html__( 'Seniors', 'learnpress' ),
			'Social Media Users'       => esc_html__( 'Social Media Users', 'learnpress' ),
			'Sports Fans'              => esc_html__( 'Sports Fans', 'learnpress' ),
			'Students'                 => esc_html__( 'Students', 'learnpress' ),
			'Tech Enthusiasts'         => esc_html__( 'Tech Enthusiasts', 'learnpress' ),
			'Travelers'                => esc_html__( 'Travelers', 'learnpress' ),
			'TV Enthusiasts'           => esc_html__( 'TV Enthusiasts', 'learnpress' ),
			'Video Creators'           => esc_html__( 'Video Creators', 'learnpress' ),
			'Writers'                  => esc_html__( 'Writers', 'learnpress' ),
		],
		'tone'                      => [
			'Analytical'     => esc_html__( 'Analytical', 'learnpress' ),
			'Argumentative'  => esc_html__( 'Argumentative', 'learnpress' ),
			'Casual'         => esc_html__( 'Casual', 'learnpress' ),
			'Conversational' => esc_html__( 'Conversational', 'learnpress' ),
			'Creative'       => esc_html__( 'Creative', 'learnpress' ),
			'Descriptive'    => esc_html__( 'Descriptive', 'learnpress' ),
			'Emotional'      => esc_html__( 'Emotional', 'learnpress' ),
			'Empathetic'     => esc_html__( 'Empathetic', 'learnpress' ),
			'Expository'     => esc_html__( 'Expository', 'learnpress' ),
			'Factual'        => esc_html__( 'Factual', 'learnpress' ),
			'Formal'         => esc_html__( 'Formal', 'learnpress' ),
			'Friendly'       => esc_html__( 'Friendly', 'learnpress' ),
			'Humorous'       => esc_html__( 'Humorous', 'learnpress' ),
			'Informal'       => esc_html__( 'Informal', 'learnpress' ),
			'Journalese'     => esc_html__( 'Journalese', 'learnpress' ),
			'Narrative'      => esc_html__( 'Narrative', 'learnpress' ),
			'Objective'      => esc_html__( 'Objective', 'learnpress' ),
			'Opinionated'    => esc_html__( 'Opinionated', 'learnpress' ),
			'Persuasive'     => esc_html__( 'Persuasive', 'learnpress' ),
			'Poetic'         => esc_html__( 'Poetic', 'learnpress' ),
			'Satirical'      => esc_html__( 'Satirical', 'learnpress' ),
			'Story-telling'  => esc_html__( 'Story-telling', 'learnpress' ),
			'Subjective'     => esc_html__( 'Subjective', 'learnpress' ),
			'Technical'      => esc_html__( 'Technical', 'learnpress' ),
		],
		'image-size-gpt-image-1'    => [
			'auto'      => esc_html__( 'Auto', 'learnpress' ),
			'1024x1024' => esc_html__( '1024x1024', 'learnpress' ),
			'1536x1024' => esc_html__( '1536x1024 (landscape)', 'learnpress' ),
			'1024x1536' => esc_html__( '1024x1536 (portrait)', 'learnpress' ),
		],
		'image-size-dall-e-2'       => [
			'256x256'   => esc_html__( '256x256', 'learnpress' ),
			'512x512'   => esc_html__( '512x512', 'learnpress' ),
			'1024x1024' => esc_html__( '1024x1024', 'learnpress' ),
		],
		'image-size-dall-e-3'       => [
			'1024x1024' => esc_html__( '1024x1024', 'learnpress' ),
			'1024x1792' => esc_html__( '1024x1792', 'learnpress' ),
			'1792x1024' => esc_html__( '1792x1024', 'learnpress' ),
		],
		'image-quality-gpt-image-1' => [
			'auto'   => esc_html__( 'Auto', 'learnpress' ),
			'high'   => esc_html__( 'High', 'learnpress' ),
			'medium' => esc_html__( 'low', 'learnpress' ),
		],
		'image-quality-dall-e-3'    => [
			'auto'     => esc_html__( 'Auto', 'learnpress' ),
			'hd'       => esc_html__( 'HD', 'learnpress' ),
			'standard' => esc_html__( 'Standard', 'learnpress' ),
		],
		'image-quality'             => [
			'auto'     => esc_html__( 'Auto', 'learnpress' ),
			'standard' => esc_html__( 'Standard', 'learnpress' ),
		],
		'image-style'               => [
			'Impressionism' => esc_html__( 'Impressionism', 'learnpress' ),
			'Cubism'        => esc_html__( 'Cubism', 'learnpress' ),
			'Surrealism'    => esc_html__( 'Surrealism', 'learnpress' ),
			'Abstract'      => esc_html__( 'Abstract', 'learnpress' ),
			'Realism'       => esc_html__( 'Realism', 'learnpress' ),
			'Expressionism' => esc_html__( 'Expressionism', 'learnpress' ),
			'Baroque'       => esc_html__( 'Baroque', 'learnpress' ),
			'Renaissance'   => esc_html__( 'Renaissance', 'learnpress' ),
			'Gothic'        => esc_html__( 'Gothic', 'learnpress' ),
			'Pop Art'       => esc_html__( 'Pop Art', 'learnpress' ),
			'Art Nouveau:'  => esc_html__( 'Art Nouveau', 'learnpress' ),
			'Minimalism'    => esc_html__( 'Minimalism', 'learnpress' ),
			'Fauvism'       => esc_html__( 'Fauvism', 'learnpress' ),
		],
		'reading_level'             => [
			'Introductory' => esc_html__( 'Introductory', 'learnpress' ),
			'Foundational' => esc_html__( 'Foundational', 'learnpress' ),
			'Intermediate' => esc_html__( 'Intermediate', 'learnpress' ),
			'Advanced'     => esc_html__( 'Advanced', 'learnpress' ),
		],
	]
);
