<?php
return apply_filters( 'lp-open-ai-language-options', array(
		'US English' => esc_html__( 'US English', 'learnpress' ),
		'UK English' => esc_html__( 'UK English', 'learnpress' ),
		'Arabic'     => esc_html__( 'Arabic', 'learnpress' ),
		'Bulgarian'  => esc_html__( 'Bulgarian', 'learnpress' ),
		'Chinese'    => esc_html__( 'Chinese', 'learnpress' ),
		'Czech'      => esc_html__( 'Czech', 'learnpress' ),
		'Danish'     => esc_html__( 'Danish', 'learnpress' ),
		'Dutch'      => esc_html__( 'Dutch', 'learnpress' ),
		'Estonian'   => esc_html__( 'Estonian', 'learnpress' ),
		'Finnish'    => esc_html__( 'Finnish', 'learnpress' ),
		'French'     => esc_html__( 'French', 'learnpress' ),
		'German'     => esc_html__( 'German', 'learnpress' ),
		'Greek'      => esc_html__( 'Greek', 'learnpress' ),
		'Hebrew'     => esc_html__( 'Hebrew', 'learnpress' ),
		'Hungarian'  => esc_html__( 'Hungarian', 'learnpress' ),
		'Indonesian' => esc_html__( 'Indonesian', 'learnpress' ),
		'Italian'    => esc_html__( 'Italian', 'learnpress' ),
		'Japanese'   => esc_html__( 'Japanese', 'learnpress' ),
		'Korean'     => esc_html__( 'Korean', 'learnpress' ),
		'Latvian'    => esc_html__( 'Latvian', 'learnpress' ),
		'Lithuanian' => esc_html__( 'Lithuanian', 'learnpress' ),
		'Norwegian'  => esc_html__( 'Norwegian', 'learnpress' ),
		'Polish'     => esc_html__( 'Polish', 'learnpress' ),
		'Portuguese' => esc_html__( 'Portuguese', 'learnpress' ),
		'Romanian'   => esc_html__( 'Romanian', 'learnpress' ),
		'Russian'    => esc_html__( 'Russian', 'learnpress' ),
		'Slovak'     => esc_html__( 'Slovak', 'learnpress' ),
		'Slovenian'  => esc_html__( 'Slovenian', 'learnpress' ),
		'Spanish'    => esc_html__( 'Spanish', 'learnpress' ),
		'Swedish'    => esc_html__( 'Swedish', 'learnpress' ),
		'Turkish'    => esc_html__( 'Turkish', 'learnpress' ),
		'Vietnamese' => esc_html__( 'Vietnamese', 'learnpress' ),
	)
);
